npm install gulp --save-dev 
npm install browser-sync --save-dev 
npm install gulp-autoprefixer --save-dev 
npm install gulp-cache --save-dev  
npm install gulp-clean-css --save-dev  
npm install gulp-rimraf --save-dev  
npm install gulp-imagemin --save-dev 
npm install gulp-plumber --save-dev  
npm install gulp-rigger --save-dev  
npm install gulp-sass --save-dev  
npm install gulp-sourcemaps --save-dev 
npm install gulp-uglify --save-dev 
npm install imagemin-jpeg-recompress --save-dev  
npm install imagemin-pngquant --save-dev  
npm install gulp-rename --save-dev  
npm install jquery --save-prod
npm install popper.js --save-prod
npm install bootstrap --save-prod